---
- name: Initial Configuration for the VM
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: true
        upgrade: dist

    - name: Install Docker deps
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Add Docker's official GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest

    - name: Ensure Docker is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Remove default NGINX site configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload nginx

    - name: Deploy NGINX reverse proxy configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/reverse_proxy.conf
      notify: Reload nginx
 
  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

