---
- name: Run Watchtower to update all containers
  hosts: all
  become: yes
  tasks:
    - name: Ensure Watchtower container is running
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        state: started
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        # The command below tells Watchtower to remove old images after update.
        command: "--cleanup"
